export const ebooks = [
  {
    id: 1,
    title: "Cẩm nang Bê tông tươi",
    category: "Vật liệu cơ bản",
    description: "Tìm hiểu toàn diện về các loại bê tông tươi, tiêu chuẩn kỹ thuật, phụ gia và ứng dụng trong các công trình dân dụng và công nghiệp.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 2,
    title: "Gạch ốp lát hiện đại",
    category: "Vật liệu hoàn thiện",
    description: "Hướng dẫn lựa chọn gạch ốp lát, phân biệt gạch Ceramic, Porcelain, Granite, cách tính toán định mức và lưu ý khi thi công.",
    image: "https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 3,
    title: "Giải pháp Cách nhiệt - Cách âm",
    category: "Vật liệu chuyên dụng",
    description: "Tổng hợp các giải pháp và vật liệu cách nhiệt, cách âm tiên tiến: Bông thủy tinh, XPS, EPS, Foam PU và ứng dụng thực tế.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 4,
    title: "Sổ tay Thép xây dựng",
    category: "Vật liệu kết cấu",
    description: "Phân loại thép, tiêu chuẩn mác thép, phương pháp bảo quản và kỹ thuật buộc cốt thép đúng chuẩn cho công trình vững chắc.",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 5,
    title: "Vật liệu xanh & Ứng dụng",
    category: "Vật liệu sinh thái",
    description: "Khám phá các loại vật liệu xây dựng thân thiện với môi trường, giảm dấu chân carbon và xu hướng kiến trúc xanh bền vững.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 6,
    title: "Thi công Sơn nước chuyên nghiệp",
    category: "Vật liệu hoàn thiện",
    description: "Bí quyết chọn sơn, quy trình thi công sơn chuẩn 5 bước, cách xử lý sự cố màng sơn và phối màu nội ngoại thất tinh tế.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 7,
    title: "Công nghệ Kính kiến trúc",
    category: "Vật liệu hoàn thiện",
    description: "Tìm hiểu về kính cường lực, kính dán an toàn, kính hộp Low-e, phụ kiện đi kèm và hướng dẫn lắp đặt vách kính cường lực.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 8,
    title: "Cẩm nang Chống thấm",
    category: "Hóa chất xây dựng",
    description: "Các nguyên nhân thấm dột thường gặp và giải pháp chống thấm triệt để cho sàn mái, tầng hầm, ban công, và khu vệ sinh.",
    image: "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 9,
    title: "Gỗ tự nhiên & Gỗ công nghiệp",
    category: "Vật liệu nội thất",
    description: "Phân biệt ván MFC, MDF, HDF, Plywood, đặc tính, độ bền và bí quyết ứng dụng gỗ công nghiệp trong thiết kế nội thất hiện đại.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 10,
    title: "Vật liệu Đóng trần - Vách ngăn",
    category: "Vật liệu nhẹ",
    description: "Hướng dẫn lựa chọn và thi công trần thạch cao, tấm ALC, panel EPS, tấm Cemboard tối ưu cho từng không gian sống.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 11,
    title: "Xi măng & Ứng dụng",
    category: "Vật liệu cơ bản",
    description: "Tìm hiểu về cấu tạo, phân loại xi măng đa dụng, xi măng chuyên dụng và kinh nghiệm trộn vữa đạt chuẩn tiêu chuẩn kỹ thuật.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 12,
    title: "Đá tự nhiên trong kiến trúc",
    category: "Vật liệu hoàn thiện",
    description: "Cẩm nang kiến thức về các dòng đá tự nhiên: Marble, Granite, Limestone, Slate cùng hướng dẫn thi công và bảo dưỡng.",
    image: "https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 13,
    title: "Vật liệu Composite",
    category: "Vật liệu công nghệ mới",
    description: "Khám phá tiềm năng của Composite, FRP trong xây dựng, lợi thế về trọng lượng, độ bền, chống ăn mòn so với vật liệu truyền thống.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 14,
    title: "Hệ thống Cửa đa năng",
    category: "Phụ kiện hoàn thiện",
    description: "Ưu nhược điểm của các hệ cửa: Nhôm kính, nhựa lõi thép, cửa thép vân gỗ, cửa cuốn và lưu ý khi chọn phụ kiện kim khí đồng bộ.",
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 15,
    title: "Ngói lợp & Tôn mạ",
    category: "Vật liệu bao che",
    description: "Bí quyết chọn vật liệu lợp mái phù hợp, từ tôn lạnh, tôn PU đến ngói thái, ngói bitum, cách thi công mái an toàn và bền bỉ.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 16,
    title: "Keo ốp lát & Chà ron",
    category: "Hóa chất xây dựng",
    description: "Giải pháp thay thế vữa xi măng truyền thống, phân tích các dòng keo dán gạch, đường ron chống thấm, chống nấm mốc.",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 17,
    title: "Vật liệu lót sàn thế hệ mới",
    category: "Vật liệu nội thất",
    description: "Cập nhật xu hướng vật liệu lót sàn nổi bật: Sàn nhựa SPC, thảm trải sàn, sàn nâng kỹ thuật và ứng dụng linh hoạt trong công trình.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 18,
    title: "Ống nước & Phụ kiện",
    category: "Vật tư M&E",
    description: "Cẩm nang lựa chọn ống nhựa uPVC, HDPE, PPR cho hệ thống cấp thoát nước, tiêu chuẩn độ dày và cách thi công ghép nối an toàn.",
    image: "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 19,
    title: "Cáp ngầm & Dây điện",
    category: "Vật tư M&E",
    description: "Các tiêu chuẩn an toàn điện quang trọng, hướng dẫn thiết kế mạng lưới điện dân dụng và hướng dẫn đi dây âm tường chuẩn kỹ thuật.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=100&w=800&h=800",
  },
  {
    id: 20,
    title: "Vật liệu Cách lửa & Chống cháy",
    category: "Vật liệu chuyên dụng",
    description: "Tầm quan trọng của vật liệu chịu lửa, các tiêu chuẩn phòng cháy chữa cháy cơ bản mới nhất và vật liệu ngăn cháy lan hiệu quả.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=100&w=800&h=800",
  }
];

